### ISSUE TITLE
API Does Not Seem to Be Working

### ISSUE THREAD

**Issue by pwdelbloomboard** [kbravh/tweet-to-markdown#6]
Greetings!  Thanks for building this.

I have attempted to use this tool on both zsh and bash with no results.

* I set the alias to the exact location have installed ttm.
* Using node 16.0.0
* Using asdf
* Using your API 

When running the command:

```
ttm --bearer <key> https://twitter.com/JoshWComeau/status/1213870628895428611
```

* As a sample, I see nothing in the current directory.  I have tried this with a variety of different tweets, options, custom file name --filename, copied to clipboard, -c, etc. and I see no results.
* Also interestingly I see no usage on the API toward my limit, though I am not seeing a, "not authorized" message from ttm.

I'm wondering if the API may take a while to be activated?

**Comment by kbravh** [comment]
Hi @pwdelbloomboard! So I've done a quick test and I've run into the problem myself. The issue is that the TTM api key has the special character `>`, which means the key needs to be wrapped in quotes:

```bash
ttm --bearer "<key>" https://twitter.com/JoshWComeau/status/1213870628895428611
```

That was a misstep on my part, and I've updated the readme to include the quotes. 

When the terminal reads the `>`, it interrupts the flow and treats your api key as an output file name. So if you check the directory you were in, you'll probably find a file with the name of your key and the text "Unauthorized" inside.

Please let me know if that helps!

**Comment by pwdelbloomboard** [comment]
Yes, it works now, thanks for updating the documentation.

I would also suggest specifying that the <key> must include the TTM> as well as the ensuing alphanumerics.
